name: Create sentry release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install && yarn build

      - uses: tclindner/sentry-releases-action@v1.2.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: alexandrecharlot
          SENTRY_PROJECT: todolist
        with:
          tagName: ${{ github.ref }}
          environment: production
          sourceMapOptions: '{"include": ["dist"]}'

      - uses: tclindner/sentry-release-deploy-action@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: alexandrecharlot
          SENTRY_PROJECT: todolist
        with:
          version: ${{ github.ref }}
          environment: production
